- name: Import GPG key NodeSource
  ansible.builtin.apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add repo NodeSource for Node.js {{ node_version }}
  ansible.builtin.apt_repository:
    repo: 'deb https://deb.nodesource.com/node_{{ node_version }} {{ ansible_distribution_release }} main'
    state: present

- name: Install Node.js {{ node_version }}
  ansible.builtin.apt:
    update_cache: yes
    name: nodejs
    state: present