credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              id: "git-credentials"
              password: "{{ git_credentials }}"
              scope: GLOBAL
              username: "volodymyrmedvetskyi"
              description: "Access token for Github repository"
          - basicSSHUserPrivateKey:
              id: "ec2-key"
              privateKeySource:
                directEntry:
                  privateKey: ${file:/var/lib/jenkins/ec2-key}
              scope: GLOBAL
              username: "ubuntu"
              description: "SSH key for AWS EC2"
          - aws:
              accessKey: "{{ access_key }}"
              id: "aws-cred"
              scope: GLOBAL
              secretKey: "{{ secret_key }}"
jenkins:
  agentProtocols:
    - "JNLP4-connect"
    - "Ping"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  disabledAdministrativeMonitors:
    - "hudson.util.DoubleLaunchChecker"
  labelAtoms:
    - name: "built-in"
  markupFormatter: "plainText"
  mode: NORMAL
  myViewsTabBar: "standard"
  nodeMonitors:
    - diskSpaceMonitor:
        freeSpaceThreshold: "1GB"
    - tmpSpace:
        freeSpaceThreshold: "1GB"
  numExecutors: 2
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 0
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
  slaveAgentPort: -1
  updateCenter:
    sites:
      - id: "default"
        url: "https://updates.jenkins.io/update-center.json"
  views:
    - all:
        name: "all"
  viewsTabBar: "standard"
globalCredentialsConfiguration:
  configuration:
    providerFilter: "none"
    typeFilter: "none"
appearance:
  prism:
    theme: PRISM
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  gitHooks:
    allowedOnAgents: false
    allowedOnController: false
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "knownHostsFileVerificationStrategy"
unclassified:

jobs:
  - file: /var/lib/jenkins/jobdsl/folders.groovy
  - file: /var/lib/jenkins/jobdsl/pipelines.groovy
