apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3MxMjM=
  MYSQL_DATABASE: bXlkYg==
  MYSQL_USER: ZGJ1c2Vy
  MYSQL_PASSWORD: ZGJ1c2VycGFzczEyMw==