---
- name: Restart Elasticsearch
  ansible.builtin.systemd:
    name: elasticsearch
    state: restarted

- name: Restart Kibana
  ansible.builtin.systemd:
    name: kibana
    state: restarted

- name: Restart Logstash
  ansible.builtin.systemd:
    name: logstash
    state: restarted